-- | Render a 'Classification' into an atom feed (the @feed.xml@ for
-- that classification).
--
-- XML is generated by 'Text' concatenation — no XML library
-- dependency. All text values passing through here go via
-- 'xmlEscape' (element text) or 'cdataWrap' (CDATA blocks inside
-- @\<content\>@).
module Bartleby.Atom
  ( renderFeed
  , xmlEscape
  , cdataWrap
  ) where

import Bartleby.Types

import Data.Function (on)
import Data.List (sortBy)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Time.Calendar (Day, showGregorian)

-- | Render a classification's atom feed.
renderFeed :: Config -> Classification -> Text
renderFeed config cls = T.concat
  [ "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  , "<feed xmlns=\"http://www.w3.org/2005/Atom\">\n"
  , renderFeedHeader config cls
  , T.concat (map (renderEntry config) entries)
  , "</feed>\n"
  ]
  where
    entries = take (cfgFeedCount config) $
      sortBy (flip compare `on` workUpdated) (allWorks cls)

allWorks :: Classification -> [Work]
allWorks c = clsWorks c ++ concatMap allWorks (clsSubs c)

------------------------------------------------------------------------
-- Feed header

renderFeedHeader :: Config -> Classification -> Text
renderFeedHeader config cls = T.concat
  [ element  "id"       (classificationLink config cls)
  , element  "title"    (xmlEscape (clsTitle cls))
  , subtitle (clsDescription cls)
  , element  "updated"  feedUpdated
  , authorElement (cfgHostname config)
  , selfLink config cls
  , alternateLink config cls
  ]
  where
    allW = allWorks cls
    feedUpdated = case allW of
      []     -> "1970-01-01T00:00:00Z"
      (_:_)  -> isoDateTime (maximum (map workUpdated allW))

subtitle :: Text -> Text
subtitle "" = ""
subtitle t  = element "subtitle" (xmlEscape t)

authorElement :: Text -> Text
authorElement hostname = T.concat
  [ "  <author><name>"
  , xmlEscape hostname
  , "</name></author>\n"
  ]

selfLink :: Config -> Classification -> Text
selfLink config cls = T.concat
  [ "  <link rel=\"self\" href=\""
  , feedSelfUri config cls
  , "\"/>\n"
  ]

alternateLink :: Config -> Classification -> Text
alternateLink config cls = T.concat
  [ "  <link rel=\"alternate\" href=\""
  , classificationLink config cls
  , "\"/>\n"
  ]

------------------------------------------------------------------------
-- Entries

renderEntry :: Config -> Work -> Text
renderEntry config w = T.concat
  [ "  <entry>\n"
  , indent2 (element "id"        (workUri config w))
  , indent2 (element "title"     (xmlEscape (workTitle w)))
  , indent2 (element "published" (isoDateTime (workCreated w)))
  , indent2 (element "updated"   (isoDateTime (workUpdated w)))
  , entryAlternateLink config w
  , indent2 ("<summary type=\"text\">"
               <> xmlEscape (workDescription w)
               <> "</summary>\n")
  , renderContent config w
  , "  </entry>\n"
  ]

entryAlternateLink :: Config -> Work -> Text
entryAlternateLink config w = T.concat
  [ "    <link rel=\"alternate\" length=\""
  , tshow (workSize w)
  , "\" href=\""
  , workUri config w
  , "\"/>\n"
  ]

renderContent :: Config -> Work -> Text
renderContent config w = case workKind w of
  WorkFile Type0 -> case workPreview w of
    Just txt -> indent2 ("<content type=\"text\">"
                          <> cdataWrap txt
                          <> "</content>\n")
    Nothing  -> ""
  WorkFile TypeI -> renderImageContent config w
  WorkFile TypeG -> renderImageContent config w
  WorkDirectory
    | T.null (workDescription w) -> ""
    | otherwise -> indent2 ("<content type=\"text\">"
                             <> xmlEscape (workDescription w)
                             <> "</content>\n")
  _ -> ""

renderImageContent :: Config -> Work -> Text
renderImageContent config w =
  let uri = workUri config w
      imgTag =
        "<img src=\"" <> xmlEscape uri
        <> "\" alt=\"" <> xmlEscape (workTitle w) <> "\"/>"
  in indent2 ("<content type=\"html\">"
                <> cdataWrap imgTag
                <> "</content>\n")

------------------------------------------------------------------------
-- URI construction

classificationLink :: Config -> Classification -> Text
classificationLink config cls =
  let base    = hostPort config
      sel     = unSelector (cfgSelector config)
      path    = T.pack (clsSourcePath cls)
      suffix  = if T.null path then "/catalog/" else "/catalog/" <> path <> "/"
  in base <> "/1" <> sel <> suffix

feedSelfUri :: Config -> Classification -> Text
feedSelfUri config cls =
  let base    = hostPort config
      sel     = unSelector (cfgSelector config)
      path    = T.pack (clsSourcePath cls)
      suffix  = if T.null path
                  then "/catalog/feed.xml"
                  else "/catalog/" <> path <> "/feed.xml"
  in base <> "/0" <> sel <> suffix

workUri :: Config -> Work -> Text
workUri config w =
  let base    = hostPort config
      sel     = unSelector (cfgSelector config)
      path    = T.pack (workSourcePath w)
      typeCh  = T.singleton (gopherTypeChar (workKind w))
  in base <> "/" <> typeCh <> sel <> "/" <> path

hostPort :: Config -> Text
hostPort config =
  "gopher://" <> cfgHostname config <> ":" <> tshow (cfgPort config)

gopherTypeChar :: WorkKind -> Char
gopherTypeChar WorkDirectory = '1'
gopherTypeChar (WorkFile t)  = case t of
  Type0 -> '0' ; Type1 -> '1' ; TypeI -> 'I' ; TypeG -> 'g'
  TypeS -> 's' ; TypeH -> 'h' ; Type9 -> '9'

------------------------------------------------------------------------
-- Escaping and primitives

-- | Escape the five XML special characters in element text: @&@, @<@,
-- @>@, @"@, and @'@. Order of replacements matters — @&@ must go
-- first so later steps don't double-escape the entities we just
-- inserted.
xmlEscape :: Text -> Text
xmlEscape =
    T.replace "'"  "&apos;"
  . T.replace "\"" "&quot;"
  . T.replace ">"  "&gt;"
  . T.replace "<"  "&lt;"
  . T.replace "&"  "&amp;"

-- | Wrap text in @\<![CDATA[ … ]]\>@. Any occurrence of @]]\>@ inside
-- the text is split across two CDATA sections via the standard
-- @]]]]\>\<![CDATA[\>@ trick so the wrapped value is always valid.
cdataWrap :: Text -> Text
cdataWrap t = "<![CDATA[" <> T.replace "]]>" "]]]]><![CDATA[>" t <> "]]>"

element :: Text -> Text -> Text
element name content = T.concat ["  <", name, ">", content, "</", name, ">\n"]

indent2 :: Text -> Text
indent2 t = "  " <> t

isoDateTime :: Day -> Text
isoDateTime d = T.pack (showGregorian d) <> "T00:00:00Z"

tshow :: Show a => a -> Text
tshow = T.pack . show
